---
# extend traefik_entrypoints with infra ports
- name: extend traefik_entrypoints with infra ports
  ansible.builtin.set_fact:
    traefik_entrypoints: "{{ traefik_entrypoints | default({}) | combine(infra_entrypoints, recursive=True) }}"
  when: infra_entrypoints | length > 0

# copy traefik config
- name: copy config for traefik
  ansible.builtin.template:
    src: dynamic_conf.yml.j2
    dest: /data/bindmounts/traefik/dynamic_conf.yml

# copy docker-compose.yml
- name: copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose-proxy.yml.j2
    dest: /home/user/docker-compose-proxy.yml

# run docker container
- name: start containers
  ansible.builtin.command: docker compose -f /home/user/docker-compose-proxy.yml up -d --remove-orphans
  when: 
    - ansible_virtualization_type != "docker"
...
